<?php if ($this->shouldInclude()): ?>
    <?php $altUniversal = $this->getAlternativeUniversalAccount(); ?>
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<?php echo $this->getUniversalAccount(); ?>',<?php echo $this->getUniversalParams(); ?>);
        <?php if ($altUniversal):?>
            ga('create', '<?php echo $altUniversal; ?>',<?php echo $this->getUniversalParams(true); ?>);
        <?php endif;?>

        <?php if($this->getUniversalAnonymise()):?>
            ga('set', 'anonymizeIp', true);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'anonymizeIp', true);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->getUniversalDisplayAdvertising()):?>
            ga('require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php endif;?>
        <?php endif;?>
        ga('send', 'pageview', '<?php echo $this->getPageName(); ?>');
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.send', 'pageview', '<?php echo $this->getPageName(); ?>');
        <?php endif;?>
        <?php if($this->getEnhancedEcommerce()):?>
            ga('require', 'ec');
        <?php endif;?>

    </script>
    <?php if($this->isSuccessPage()):?>
        <?php $order = $this->_getOrder();?>
        <?php
            if($this->getEnhancedEcommerce()):
                // enhanced ecommerce code goes here
            ?>
                <script>
                    /* <![CDATA[ */
                    <?php $transactionDetails = "{
                       'id': '".$this->jsQuoteEscape($order->getIncrementId()) ."',
                       'affiliation': '". $this->jsQuoteEscape(Mage::app()->getStore()->getName()) ."',
                       'revenue': '". Mage::helper('googleanalyticsplus')->convert($order, 'grand_total') ."',
                       'shipping': '". Mage::helper('googleanalyticsplus')->convert($order, 'shipping_amount') ."',
                       'tax': '". Mage::helper('googleanalyticsplus')->convert($order, 'tax_amount') ."',
                       'currency': '". Mage::helper('googleanalyticsplus')->getTrackingCurrency($order) ."'
                       }";
                   ?>
                    ga('ec:setAction', 'purchase', <?php echo $transactionDetails?>);
                    <?php foreach ($order->getAllVisibleItems() as $item):?>

                    <?php $itemDetails = "{
                                'id': '".$this->jsQuoteEscape($item->getSku()) ."',
                                'name': '". $this->jsQuoteEscape($item->getName()) ."',
                                'sku': '". $this->jsQuoteEscape($item->getSku()) ."',
                                'price': '". Mage::helper('googleanalyticsplus')->convert($item, 'price', $order->getOrderCurrencyCode()) ."',
                                'quantity': '". (int)$item->getQtyOrdered() ."',
                                'category': '". $this->jsQuoteEscape($this->getCategory($item)) ."'
                                }";
                    ?>
                    ga('ec:addProduct', <?php echo $itemDetails?>);
                    <?php endforeach;?>
                    ga('send', 'pageview');
                    /* ]]> */
                </script>
            <?php
            else:
                // ecommerce.js based code goes here
            ?>
                <script>
                /* <![CDATA[ */
                ga('require', 'ecommerce', 'ecommerce.js');
                <?php if ($altUniversal):?>
                    ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'ecommerce', 'ecommerce.js');
                <?php endif;?>

                 <?php $transactionDetails = "{
                    'id': '".$this->jsQuoteEscape($order->getIncrementId()) ."',
                    'affiliation': '". $this->jsQuoteEscape(Mage::app()->getStore()->getName()) ."',
                    'revenue': '". Mage::helper('googleanalyticsplus')->convert($order, 'grand_total') ."',
                    'shipping': '". Mage::helper('googleanalyticsplus')->convert($order, 'shipping_amount') ."',
                    'tax': '". Mage::helper('googleanalyticsplus')->convert($order, 'tax_amount') ."',
                    'currency': '". Mage::helper('googleanalyticsplus')->getTrackingCurrency($order) ."'
                    }";
                ?>

                ga('ecommerce:addTransaction', <?php echo $transactionDetails?>);
                <?php if ($altUniversal):?>
                    ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ecommerce:addTransaction', <?php echo $transactionDetails?>);
                <?php endif;?>


                <?php foreach ($order->getAllVisibleItems() as $item):?>

                    <?php $itemDetails = "{
                                'id': '".$this->jsQuoteEscape($order->getIncrementId()) ."',
                                'name': '". $this->jsQuoteEscape($item->getName()) ."',
                                'sku': '". $this->jsQuoteEscape($item->getSku()) ."',
                                'price': '". Mage::helper('googleanalyticsplus')->convert($item, 'price', $order->getOrderCurrencyCode()) ."',
                                'quantity': '". (int)$item->getQtyOrdered() ."',
                                'category': '". $this->jsQuoteEscape($this->getCategory($item)) ."'
                                }";
                    ?>


                    ga('ecommerce:addItem', <?php echo $itemDetails?>);
                    <?php if ($altUniversal):?>
                        ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ecommerce:addItem', <?php echo $itemDetails?>);
                    <?php endif;?>
                <?php endforeach;?>
                ga('ecommerce:send');
                <?php if ($altUniversal):?>
                    ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ecommerce:send');
                <?php endif;?>
                /* ]]> */
                </script>
            <?php endif; ?>

    <?php endif; ?>
    <!-- End Google Analytics -->
<?php endif; ?>
